"""
企业微信 KPI 消息卡片集成
WeChat Work (Wecom) Card Integration for KPI Reports

将 KPI 考核方案以企业微信消息卡片形式发送。
"""

import json
import re
import sys
import os

# 添加父目录到路径（支持跨目录导入）
_local_dir = os.path.dirname(os.path.abspath(__file__))
# 添加当前包目录到 sys.path，确保内部模块可导入
if _local_dir not in sys.path:
    sys.path.insert(0, _local_dir)

from kpi_engine import KPIPerformanceEngine, KPIResult


def build_kpi_wecom_card(
    position: str,
    sub_type: str = None,
    period: str = "季度",
    engine: KPIPerformanceEngine = None,
) -> dict:
    """
    构建企业微信 KPI 卡片消息

    Args:
        position: 岗位类型
        sub_type: 子类型
        period: 考核周期
        engine: KPIPerformanceEngine 实例

    Returns:
        dict: 企业微信卡片消息体
    """
    if engine is None:
        engine = KPIPerformanceEngine()

    # 生成绩效考核方案
    result = engine.generate(
        position=position,
        sub_type=sub_type,
        period=period,
        format="json",
    )

    if isinstance(result, dict) and result.get("error"):
        return None

    kpi_result: KPIResult = _dict_to_result(result)

    # 构建指标摘要（取前5个最重要的）
    indicator_lines = []
    for cat in kpi_result.categories:
        for ind in cat.indicators[:5]:
            indicator_lines.append({
                "title": f"{ind.name}（权重{ind.weight}%）",
                "value": f"目标：{ind.target}"
            })

    # 构建卡片元素
    elements = []

    # 1. 标题区域
    elements.append({
        "tag": "markdown",
        "content": f"### 🏦 **银行{result['sub_type']} {result['period']}绩效考核方案**\n"
                   f"**岗位类型：** {result['position']} | **考核周期：** {result['period']} | "
                   f"**总分权重：** {result['total_weight']}%"
    })

    # 2. 分隔线
    elements.append({"tag": "hr"})

    # 3. KPI指标表格
    kpi_table_md = "**【KPI指标】**\n\n"
    kpi_table_md += "| 指标名称 | 权重 | 目标值 | 评分方法 |\n"
    kpi_table_md += "|----------|------|--------|----------|\n"

    for cat in kpi_result.categories:
        for ind in cat.indicators:
            # 截断过长的文本
            target_short = ind.target[:15] + "..." if len(ind.target) > 15 else ind.target
            scoring_short = ind.scoring_method[:12] + "..." if len(ind.scoring_method) > 12 else ind.scoring_method
            kpi_table_md += f"| {ind.name} | {ind.weight}% | {target_short} | {scoring_short} |\n"

    elements.append({
        "tag": "markdown",
        "content": kpi_table_md
    })

    # 4. 考核规则
    rules_short = result['assessment_rules'][:80].replace("\n", " ") + "..."
    elements.append({
        "tag": "markdown",
        "content": f"**【考核规则】** {rules_short}"
    })

    # 5. 改进建议
    suggestions_md = "**【改进建议】**\n"
    for i, sug in enumerate(result['improvement_suggestions'][:3], 1):
        suggestions_md += f"{i}. {sug}\n"

    elements.append({
        "tag": "markdown",
        "content": suggestions_md
    })

    # 6. 底部
    elements.append({
        "tag": "markdown",
        "content": "> 📅 由 **KPI 绩效考核引擎 v1.0** 自动生成"
    })

    # 构建完整卡片
    card = {
        "msgtype": "interactive",
        "interactive": {
            "card_type": "template_card",
            "source": {
                "icon_url": "https://example.com/icon.png",
                "desc": "KPI绩效引擎"
            },
            "main_title": {
                "title": f"{kpi_result.sub_type} {kpi_result.period}绩效考核方案",
                "desc": f"岗位：{kpi_result.position} | 周期：{kpi_result.period}"
            },
            "emphasis1": {
                "title": f"💰 KPI 维度权重：{kpi_result.total_weight}%",
                "desc": "查看完整方案请访问系统"
            },
            "quote_area": {
                "title": "考核重点",
                "quote_text": _build_emphasis_text(kpi_result),
            },
            "sub_title_text": f"Generated by KPI Engine v1.0 | {kpi_result.sub_type}",
            "card_action": {
                "type": 1,  # view类型
                "url": "https://example.com/kpi-system",  # 实际系统中替换为真实URL
            },
            "elements": elements,
        }
    }

    return card


def _dict_to_result(d: dict) -> KPIResult:
    """将字典转换为 KPIResult 对象"""
    from dataclasses import replace
    from kpi_engine import KPICategory, KPIIndicator

    cats = []
    for cat_dict in d.get("categories", []):
        inds = []
        for ind_dict in cat_dict.get("indicators", []):
            inds.append(KPIIndicator(**ind_dict))
        cats.append(KPICategory(
            dimension=cat_dict["dimension"],
            category_weight=cat_dict.get("category_weight", 0.0),
            indicators=inds,
        ))

    return KPIResult(
        position=d["position"],
        sub_type=d["sub_type"],
        period=d["period"],
        categories=cats,
        total_weight=d.get("total_weight", 100.0),
        assessment_rules=d.get("assessment_rules", ""),
        data_requirements=d.get("data_requirements", []),
        improvement_suggestions=d.get("improvement_suggestions", []),
    )


def _build_emphasis_text(kpi_result: KPIResult) -> str:
    """构建引用区域的强调文字"""
    parts = []
    for cat in kpi_result.categories:
        for ind in cat.indicators[:3]:
            parts.append(f"▶ {ind.name}（{ind.weight}%）")
    return " | ".join(parts[:3])


def build_kpi_summary_card(
    position: str,
    sub_type: str = None,
    period: str = "季度",
    engine: KPIPerformanceEngine = None,
) -> dict:
    """
    构建简洁版 KPI 摘要卡片（适合通知推送）
    """
    if engine is None:
        engine = KPIPerformanceEngine()

    result = engine.generate(
        position=position,
        sub_type=sub_type,
        period=period,
        format="json",
    )

    if isinstance(result, dict) and result.get("error"):
        return None

    # 摘要版卡片
    card = {
        "msgtype": "text"
    }

    # 生成文本摘要
    summary_text = (
        f"📊 **KPI考核方案已生成**\n\n"
        f"岗位：{result['sub_type']}\n"
        f"周期：{result['period']}\n"
        f"维度：\n"
    )

    for cat in result.get("categories", []):
        for ind in cat.get("indicators", [])[:4]:
            summary_text += f"  • {ind['name']}（{ind['weight']}%）\n"

    summary_text += f"\n💡 改进建议：{result['improvement_suggestions'][0] if result.get('improvement_suggestions') else '持续优化'}"
    card["text"] = summary_text

    return card


# ============================================================
# CLI 入口
# ============================================================

def main():
    """CLI 入口：生成并打印卡片 JSON"""
    import argparse

    parser = argparse.ArgumentParser(description="生成企业微信 KPI 卡片")
    parser.add_argument("position", help="岗位类型（如 客户经理）")
    parser.add_argument("--sub", dest="sub_type", default=None, help="子类型（如 零售客户经理）")
    parser.add_argument("--period", default="季度", help="考核周期（季度/月度）")
    parser.add_argument("--summary", action="store_true", help="使用摘要版卡片")
    parser.add_argument("--pretty", action="store_true", help="格式化输出")

    args = parser.parse_args()

    if args.summary:
        card = build_kpi_summary_card(
            position=args.position,
            sub_type=args.sub_type,
            period=args.period,
        )
    else:
        card = build_kpi_card(
            position=args.position,
            sub_type=args.sub_type,
            period=args.period,
        )

    if card is None:
        print("❌ 生成卡片失败，请检查参数", file=sys.stderr)
        sys.exit(1)

    indent = 2 if args.pretty else None
    print(json.dumps(card, ensure_ascii=False, indent=indent))


# 兼容函数别名
def build_kpi_card(position, sub_type=None, period="季度", engine=None):
    """别名：build_kpi_wecom_card"""
    return build_kpi_wecom_card(position, sub_type, period, engine)


if __name__ == "__main__":
    main()
