"""
WeCom Integration - 企业微信卡片输出
将智能投顾方案以企业微信消息卡片格式输出
"""

import json
from typing import Dict, Any, Optional


class WeComRoboAdvisorCard:
    """
    智能投顾企业微信卡片输出
    生成符合企业微信消息卡片格式的投顾方案
    """

    def __init__(self):
        self.card_version = "1.0"

    def build_advisory_card(self, advisory_result: dict) -> dict:
        """
        将投顾方案构建为企业微信卡片
        """
        risk = advisory_result.get("risk_profile", {})
        alloc = advisory_result.get("asset_allocation", {})
        portfolio = advisory_result.get("portfolio", {})
        rebalancing = advisory_result.get("rebalancing", {})
        compliance = advisory_result.get("compliance", {})
        summary = advisory_result.get("summary", "")

        # 聚合配置
        strategic = alloc.get("strategic", {})
        stocks_pct = strategic.get("stocks", "0%")
        bonds_pct = strategic.get("bonds", "0%")
        alts_pct = strategic.get("alternatives", "0%")
        cash_pct = strategic.get("cash", "0%")

        # 指标
        er = portfolio.get("expected_return", "0%")
        vol = portfolio.get("expected_volatility", "0%")
        sharpe = portfolio.get("sharpe_ratio", "0")
        var95 = portfolio.get("var_95", "0%")

        # 头部配色：稳健-蓝，平衡-橙，进取/激进-红，保守-绿
        risk_color_map = {
            "保守型": "#2E7D32",
            "稳健型": "#1565C0",
            "平衡型": "#E65100",
            "进取型": "#C62828",
            "激进型": "#880E4F",
        }
        header_color = risk_color_map.get(risk.get("risk_type", ""), "#1565C0")

        card = {
            "msgtype": "interactive",
            "card": {
                "card_type": "news",
                "source": {
                    "icon_url": "https://xxx/robo_advisor_icon.png",
                    "desc": "智能投顾引擎 v1.0",
                },
                "action": {
                    "app_link": "",
                },
                "basic": {
                    "title": f"📊 智能投顾方案 | {risk.get('risk_type', '稳健型')}",
                    "desc": summary,
                    "emphasis_title": f"{risk.get('risk_type', '稳健型')} · {risk.get('investment_goal', '增值')} · 评分{risk.get('risk_score', 50)}分",
                    "quote_color": header_color,
                },
                "components": {
                    "type": "card",
                    "card": {
                        "type": "free_markdown",
                        "free_markdown": {
                            "tag": "markdown",
                            "content": self._build_allocation_md(alloc),
                        },
                    },
                },
                "jump_list": [
                    {
                        "title": "📈 组合指标",
                        "desc": f"预期收益 {er} | 波动率 {vol} | 夏普 {sharpe} | VaR(95%) {var95}",
                        "type": "url",
                        "url": "",
                    },
                    {
                        "title": "⚖️ 再平衡计划",
                        "desc": f"{rebalancing.get('strategy', '季度再平衡')} | 下次 {rebalancing.get('next_rebalance_date', 'TBD')}",
                        "type": "url",
                        "url": "",
                    },
                    {
                        "title": "⚠️ 风险提示",
                        "desc": compliance.get("risk_disclosure", ["市场有风险"])[0],
                        "type": "url",
                        "url": "",
                    },
                ],
                "footer": {
                    "desc": " Generated by Robo Advisor Engine",
                    "logo_url": "https://xxx/robot_icon.png",
                },
            },
        }

        return card

    def _build_allocation_md(self, alloc: dict) -> str:
        """构建资产配置 Markdown 内容"""
        strategic = alloc.get("strategic", {})
        detail = alloc.get("detail", {})
        region = alloc.get("region", {})

        md = "### 🎯 战略资产配置\n\n"
        md += f"| 资产类别 | 目标配置 |\n|---|---|\n"
        for k, v in strategic.items():
            emoji_map = {"stocks": "📈", "bonds": "📉", "alternatives": "💎", "cash": "💵"}
            emoji = emoji_map.get(k, "📦")
            md += f"| {emoji} {k} | **{v}** |\n"

        md += "\n### 🌍 区域配置\n\n"
        for k, v in region.items():
            md += f"- {k}: **{v}**\n"

        md += "\n### 📋 详细配置\n\n"
        for k, v in detail.items():
            if float(v.rstrip("%")) > 0.1:
                md += f"- {k}: {v}\n"

        return md

    def build_rebalance_alert_card(self, rebalance_result: dict) -> dict:
        """构建再平衡预警卡片"""
        alerts = rebalance_result.get("drift_alerts", [])

        content = "### ⚠️ 再平衡预警\n\n"
        content += "| 资产 | 当前 | 目标 | 偏离 | 操作 |\n"
        content += "|---|---|---|---|---|\n"
        for alert in alerts[:5]:
            content += f"| {alert.get('asset_name', alert.get('asset_key', ''))} "
            content += f"| {alert.get('current_pct', '')} "
            content += f"| {alert.get('target_pct', '')} "
            content += f"| {alert.get('drift', '')} "
            content += f"| {'🔴减配' if alert.get('action') == '减配' else '🟢增配'} |\n"

        return {
            "msgtype": "interactive",
            "card": {
                "card_type": "news",
                "basic": {
                    "title": "⚠️ 投资组合再平衡提醒",
                    "desc": f"共检测到 {len(alerts)} 项偏离",
                    "emphasis_title": "再平衡提醒",
                },
                "components": {
                    "type": "card",
                    "card": {
                        "type": "free_markdown",
                        "free_markdown": {"tag": "markdown", "content": content},
                    },
                },
            },
        }

    def output_json(self, card: dict) -> str:
        """输出卡片 JSON"""
        return json.dumps(card, ensure_ascii=False, indent=2)


# ─── CLI 入口 ────────────────────────────────────────────────────────────────

def main():
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    from robo_advisor_engine import RoboAdvisorEngine

    if len(sys.argv) < 3:
        print("Usage: python3 wecom_integration.py advisory '智能投顾 稳健型 资产100万'", file=sys.stderr)
        print("Usage: python3 wecom_integration.py rebalance '<rebalance_result_json>'", file=sys.stderr)
        sys.exit(1)

    import os
    cmd = sys.argv[1].lower()
    card_builder = WeComRoboAdvisorCard()

    if cmd == "advisory":
        user_input = sys.argv[2]
        engine = RoboAdvisorEngine()
        result = engine.generate_advisory(user_input)
        card = card_builder.build_advisory_card(result)
    elif cmd == "rebalance":
        import json
        result = json.loads(sys.argv[2])
        card = card_builder.build_rebalance_alert_card(result)
    else:
        print(f"Unknown: {cmd}", file=sys.stderr)
        sys.exit(1)

    print(card_builder.output_json(card))


if __name__ == "__main__":
    import os, sys
    main()
